### ISSUE TITLE
Plugin isn't included on ChaiJS website

### ISSUE THREAD

**Issue by JamesMessinger** [JS-DevTools/chai-exec#2]
The ChaiJS website has a [plugins page](https://www.chaijs.com/plugins/) that lists all(?) chai plugins, but chai-exec isn't in the list.

@keithamus - What does it take to get added to that page?  I _thought_ it was just a matter of adding the `chai` and `chai-plugin` keywords to package.json.

https://github.com/JS-DevTools/chai-exec/blob/f0032644803a9fa3dac8ae8550e9782de29a921e/package.json#L5-L7

**Comment by keithamus** [comment]
Thanks for pinging me @JamesMessinger!

It _was_ just a matter of adding those keywords, but there was an error in the nightly job which has now been fixed. `chai-exec` is now listed on the site: https://www.chaijs.com/plugins/chai-exec/

**Comment by JamesMessinger** [comment]
Sweet!  Thanks @keithamus !
